const ITEM_GROUPS = {
    "Ulepy": {
        "1-100": [
            "Rybia Ość",
            "Biała Perła",
            "Niebieska Perła",
            "Krwawa Perła",
            "Futro Yeti",
            "Kawałek Lodu",
            "Matowy Lód"
        ],
        "100-150": [
            "Symbol Wojownika",
            "Krew Małpy",
            "Pustynny Piasek",
            "Nici",
            "Wątroba Gigant Maga",
            "Talizman Lorda Małp",
            "Posępna Drewniana Maska",
            "Czarny Lód",
            "Kamień Duszy Jinunggyi",
            "Pierścień Króla Wobby",
            "Złota Perła",
            "Odłamek Diabła"
        ],
        "150-200": [
            "Ezoteryczny Przewodnik",
            "Zardzewiałe Ostrze",
            "Mistyczne Zioło",
            "Księga Klątw",
            "Nieznany Talizman",
            "Język Żaby",
            "Legendarny Pamiętnik",
            "Kropla Krwi",
            "Mleczny Sok",
            "Order Czerwonego Wodza",
            "Szmaragdowa Perła",
            "Rubinowa Perła",
            "Lazurytowa Perła",
            "Czerwone Pióro"
        ],
        "200-250": [
            "Klejnot Demona",
            "Liść Ostępów",
            "Demoniczne Prochy",
            "Magiczne Nasiona",
            "Kamień Beran-Setaou",
            "Broszura Szermierki",
            "Instr. Dwuręcz. Miecza",
            "Instr. Jednoręcz. Miecza",
        ],
        "251-253": [
            "Oczy Pająka",
            "Kieł Wylmira",
            "Księga Ogrów",
            "Notatka Przywódcy",
            "Olejek Piżmowy",
            "Amulet Wyklętych",
            "Zaczarowany Popiół",
            "Skamieniała Łza",
            "Obsydian",
            "Łzy Baljit-Elvedin",
            "Kość Palca Azraela",
            "Maczuga z Amanu",
            "Piasek Kwarcowy",
            "Wodny Kryształ",
            "Księżycowy Kryształ",
            "Kamień Duszy Aurtumryu",
            "Kamień Duszy Gyimok",
            "Kamień Duszy Tugyi",
            "Kamień Duszy Lasu",
            "Kryształ Króla Lemura",
            "Czerw. Piasek Kwarc.",
            "Piasek Pustynny",
            "Papirus Mądrości",
            "Pancerz Kraba",
            "Krew Ofiarna",
            "Peleryna Bohatera",
            "Kamień Maat",
            "Bagienny Piasek",
            "Kleszcz Kraba",
            "Korzeń Nirnu",
            "Pazur Mantykory",
            "Klejnot Ziel. Smoka",
            "Krew Czerw. Smoka",
            "Trucizna Wyklętych"
        ],
        "254": [
            "Łuska Rubinowego Prasmoka",
            "Rdzeń Mocy Legend",
            "Pióro Hedwigi",
            "Antidotum Infekcji",
            "Krew Plagi Yonwan",
            "Próbka Szlamu",
            "Klejnot Azarona",
            "Muszla Cthulu",
            "Klejnot Octopusa",
            "Zwój Wiecznego Łowcy",
            "Rdzeń Kamienia Duszy"
        ],
        "Other": [
            "Dzban Esencji Utnuk",
            "Gwiezdny Pył",
            "Tęczowa Perła",
            "Odznaka Yang Shina",
            "Eliksir Baek-Go I",
            "Eliksir Baek-Go II",
            "Eliksir Baek-Go III",
            "Eliksir Baek-Go IV",
            "Eliksir Baek-Go V",
            "Eliksir Baek-Go VI",
            "Eliksir Baek-Go VII",
            "Mieszanka Baek-Go VI",
            "Mieszanka Baek-Go VII",
            "Kociołek Baek-Go"
        ]
    },
    "Łowienie": {
        "Łowienie": [
            "Taj. Szafirowa Skrzynia",
            "Ikra Pospolitej Ryby",
            "Ikra Rzadkiej Ryby",
            "Ikra Legendarnej Ryby",
            "Karaś",
            "Ryba Mandaryna",
            "Duży Karaś",
            "Karp",
            "Łosoś",
            "Amur",
            "Pstrąg",
            "Węgorz",
            "Tęczowy Pstrąg",
            "Rzeczny Pstrąg",
            "Krasnopiórka",
            "Okoń",
            "Tenchi",
            "Sum",
            "Piskorz",
            "Ryba Lotosu",
            "Słodka Ryba",
            "Gromadnik",
            "Shiri",
            "Lustrzany Karp",
            "Złoty Karaś",
            "Okoń Czerwony",
            "Różanka",
            "Srebrzyk",
            "Złotnica",
            "Błazenek",
            "Welonica",
            "Pstrąg Tygrysi",
            "Płazenica",
            "Skrętnica"
        ]
    }
}